import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <Link href="/about">
        <a>About</a>
      </Link>
    </nav>

      <main >
       <h1>Hello Jerens</h1>
      </main>

      <footer >

      </footer>
    </div>
  )
}

export default Home
