import { Contribution } from '@/types/contributions'

export const Contributions: Contribution[] = [
    {
        organization: 'Servo',
        project: 'Servo',
        issue_name: 'Empty',
        issue_number: '0',
        issue_url: 'https://github.com/servo/servo/issues',
        pr_name:
            'mach: Enable ANN rules (type annotations) for ruff Python linter',
        pr_number: '38531',
        pr_url: 'https://github.com/servo/servo/pull/38531',
        date: '14 August 2025',
        status: 'merged',
    },
    {
        organization: 'Servo',
        project: 'Servo',
        issue_name: 'Enable GitHub annotations for cargo-clippy on the CI',
        issue_number: '37231',
        issue_url: 'https://github.com/servo/servo/issues/37231',
        pr_name: 'Mach clippy & test-tidy github inline annotation',
        pr_number: '37294',
        pr_url: 'https://github.com/servo/servo/pull/37294',
        date: '23 June 2025',
        status: 'merged',
    },
    {
        organization: 'Meshery',
        project: 'Meshery',
        issue_name: 'Empty',
        issue_number: '0',
        issue_url: 'https://github.com/meshery/meshery/issues',
        pr_name: 'ci: add e2e test report using gh comment on PR',
        pr_number: '11697',
        pr_url: 'https://github.com/meshery/meshery/pull/11629',
        date: '19 August 2024',
        status: 'merged',
    },
    {
        organization: 'Meshery',
        project: 'Meshery',
        issue_name:
            '[Docs] Step to set up environment variables missing in the docs for contributing to end-to-end playwright tests',
        issue_number: '11230',
        issue_url: 'https://github.com/meshery/meshery/issues/11230',
        pr_name: '[DOCS] Contributing E2E Test',
        pr_number: '11629',
        pr_url: 'https://github.com/meshery/meshery/pull/11629',
        date: '13 August 2024',
        status: 'merged',
    },
    {
        organization: 'AsyncApi',
        project: 'Modelina',
        issue_name: 'Make Playground Mobile Responsive',
        issue_number: '1715',
        issue_url: 'https://github.com/asyncapi/modelina/issues/1715',
        pr_name: 'style(website): make Playground Mobile Responsive',
        pr_number: '2028',
        pr_url: 'https://github.com/asyncapi/modelina/pull/2028',
        date: '7 June 2024',
        status: 'merged',
    },
    {
        organization: 'AsyncApi',
        issue_name: 'Make Playground Mobile Responsive',
        issue_number: '1715',
        project: 'Modelina',
        issue_url:
            'https://github.com/asyncapi/modelina/pull/2028#discussion_r1632703345',
        pr_name:
            'chore(website): configure eslint config similiar to asyncapi website',
        pr_number: '2031',
        pr_url: 'https://github.com/asyncapi/modelina/pull/2031',
        date: '10 June 2024',
        status: 'merged',
    },
]
