name: Lighthouse CI

on:
    workflow_call:
        inputs:
            static_web_url:
                required: true
                type: string

jobs:
    lhci:
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@v2.11.0
              with:
                  egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@v4.1.7
            - name: Install pnpm
              uses: pnpm/action-setup@v4.1.0
            - name: Setup Node.js 18.x
              uses: actions/setup-node@v4.3.0
              with:
                  node-version-file: '.nvmrc'
            - name: 'Lighthouse CI assertion'
              id: lhci
              shell: bash
              run: |
                  pnpm add -g @lhci/cli@0.11.x
                  echo -e "\n"
                  echo "Start collecting LH report..."
                  lhci collect --url=${{ inputs.static_web_url }} --url=${{ inputs.static_web_url }}/blog --url=${{ inputs.static_web_url }}/project -n=4
                  echo -e "\n"
                  echo "Start asserting LH score..."
                  lhci assert --config=./.lighthouserc.json
                  echo -e "\n"
                  echo "Start uploading the report..."
                  lhci upload --target "temporary-public-storage" --githubAppToken "$LHCI_GITHUB_APP_TOKEN" --githubToken "$GITHUB_TOKEN"
              env:
                  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
